### ISSUE TITLE
Lab 4 - Missing include

### ISSUE THREAD

**Issue by rbuenviaje** [rpcme/afr-workshop-cc3220sf#16]
Seems like `#include "semphr.h"` needs to be added to `aws_hello_world.c` or I receive errors when adding `SemaphoreHandle_t xSemaphore;` in https://github.com/rpcme/afr-workshop-cc3220sf/blob/master/Lab4.md#initialize-the-mutex-semaphore

**Comment by rpcme** [comment]
This was fixed during the workshop to the end of the section "The Accelerometer Task".
