### ISSUE TITLE
Feedback - thingId

### ISSUE THREAD

**Issue by adarshdy** [rpcme/afr-workshop-cc3220sf#2]
Lab 1: Create the 'Thing' Virtual Devices > step 4 
Comment: The CLI output probably gives the thingId as well.

**Comment by rpcme** [comment]
I am clarifying the text - I hope that will help.
There isn't a "thingId" - there is ThingName, ThingARN, and ClientId.  ClientId does not have to be the same as ThingName, but it helps when making more prescriptive Thing Policies.
