### ISSUE TITLE
Feedback - popd

### ISSUE THREAD

**Issue by adarshdy** [rpcme/afr-workshop-cc3220sf#5]
Lab 1: Download the Root CA.
wget -O rootca.pem \
     https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem
popd

Comment: What is the reason for the popd command?

**Comment by rpcme** [comment]
ah, this is a leftover from another lab i wrote. will remove.
