### ISSUE TITLE
Additional Clarity - policy file

### ISSUE THREAD

**Issue by adarshdy** [rpcme/afr-workshop-cc3220sf#9]
Issue: 
Lab 1
Section: Create the Gateway's Policy
In this step, you will setup a policy to grant appropriate permissions for your Thing when authenticating with the Certificate.
**Create the policy file on the device.
vi ${THING_NAME}_policy.json**

Comment: Where exactly should the policy file be created?

**Comment by rpcme** [comment]
fixed by commit 93cdb7c
